### ISSUE TITLE
Como developer quiero disponer de una capa de acceso a datos para los pedidos

### ISSUE THREAD

**Issue by agonsant** [software-craftsmanship-10-2022/mcdonalds-coders-app#6]

**Comment by agonsant** [comment]
Actualmente la información de los productos se obtiene directamente de un archivo, en la propia aplicación y las operaciones con dichos productos se gestionan directamente en la interfaz

Queremos transformar la aplicación para abstraer a la aplicación el detalle de implementación sobre cómo se gestionan los pedidos y sus operaciones.

Refactoriza la aplicación para desacoplar la interfaz y la capa de acceso a datos y  sus operaciones.

Tendremos que realizar lo siguiente:

- Construir el archivo con un API pública que permita realizar las diferentes operaciones con los pedidos. Estas operaciones deben ser asíncronas (aunque vengan de un archivo local) ya que en un podríamos migrar a API
- Construir un custom hook para exponer a la interfaz las operaciones necesarios
- El sistema debe ser cacheable y persistir en este caso en alguno de los mecanismos del Browser (LocalStorage, Session o IndexedDB)
- Refactoriza para que utilicen el nuevo sistema

PD: No te olvides de usar TDD

**Comment by davidnotplay** [comment]
Este diagrama reorganiza los tipos y mejora las futuras funcionalidades (añadir al menú retirar/añadir extras)

![Image](https://user-images.githubusercontent.com/2668489/200172520-5c5f006e-4334-4552-ab4d-805b9a7eaa57.png)
